name: Project Validation

on:
  push:
  pull_request:

jobs:
  manifest:
    name: Generate manifest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate manifest
        run: |
          node -v
          if [ -f scripts/generate_manifest.js ]; then
            node scripts/generate_manifest.js
          else
            echo "scripts/generate_manifest.js not found."
          fi

      - name: Upload manifest artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-manifest
          path: project-manifest.json
          if-no-files-found: warn

  checks:
    name: TypeScript and Next build checks (conditional)
    runs-on: ubuntu-latest
    if: ${{ hashFiles('package.json') != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm install --frozen-lockfile
          elif [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: TypeScript noEmit check
        run: |
          npx tsc --noEmit || true

      - name: Lint (if available)
        run: |
          npm run lint || true

      - name: Next build (if available)
        run: |
          npm run build || npx next build || true

      - name: API routes harness
        env:
          THESYS_API_KEY: ${{ secrets.THESYS_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_CX: ${{ secrets.GOOGLE_CX }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          node scripts/test_api_routes.js || true

      - name: Upload API routes report
        uses: actions/upload-artifact@v4
        with:
          name: api-routes-report
          path: api-routes-report.json
          if-no-files-found: warn